version: '3.5'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: container_elasticsearch_7_5_0
    ports:
      - 9200:9200
    networks:
      - custom_network
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx4g"
    volumes:
      - type: volume
        source: volume-container-elasticsearch-data-stock-market
        target: /usr/share/elasticsearch/data_stock_market

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: container_kibana_7_5_0
    ports:
      - 5603:5601
    networks:
      - custom_network
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://container_elasticsearch_7_5_0:9200/"


networks:
  custom_network:
    name: "custom_network"
    driver: "bridge"

volumes:
  volume-container-elasticsearch-data-stock-market:
    name: "volume-container-elasticsearch-data-stock-market"
