version: '3.5'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: container_elasticsearch_7_5_0
    ports:
      - "9200:9200"  # Expose port 9200 to host
    networks:
      - custom_network
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx4g"
    volumes:
      - type: volume
        source: volume-container-elasticsearch-data-stock-market
        target: /usr/share/elasticsearch/data_stock_market

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: container_kibana_7_5_0
    ports:
      - "5601:5601"  # Expose port 5601 to host for Kibana UI
    networks:
      - custom_network
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://container_elasticsearch_7_5_0:9200/"

  webserver:
    image: image_stock_market_webserver
    container_name: container_stock_market_webserver
    build: .
    ports:
      - "8080:8080"  # Expose port 8080 to the host
    networks:
      - custom_network  # Connect to custom network to access Elasticsearch
    environment:
      elasticsearch_host: container_elasticsearch_7_5_0  # Use the container name of Elasticsearch
      elasticsearch_port: 9200
      kibana_host: container_kibana_7_5_0
      kibana_port: 5601
    env_file:
      - .env
    volumes:
      - /Users/bomfly/Projects/stock-market/data:/usr/flask-app/data
      - /Users/bomfly/Projects/stock-market/logs:/usr/flask-app/logs

networks:
  custom_network:
    name: "custom_network"
    driver: "bridge"  # Default bridge mode for inter-container communication

volumes:
  volume-container-elasticsearch-data-stock-market:
    name: "volume-container-elasticsearch-data-stock-market"
